# Generated by Django 5.1.3 on 2024-11-15 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apps_utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cantidad_mb', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('detail', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'plans',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'services',
            },
        ),
        migrations.CreateModel(
            name='StateSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('tag', models.CharField(max_length=50)),
                ('detail', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'state_sales',
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_utils.clients')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_sales.plans')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_sales.services')),
                ('estate_sales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_sales.statesales')),
            ],
            options={
                'db_table': 'sales',
            },
        ),
    ]
