# Generated by Django 5.1.3 on 2024-11-15 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cajas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('direction', models.CharField(max_length=300)),
                ('img_eart', models.CharField(max_length=400)),
                ('img_caja', models.CharField(max_length=400)),
                ('detail', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Distritos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=100)),
                ('detail', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='StateOnu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=100)),
                ('detail', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'state_onu',
            },
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('user', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('distrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_utils.distritos')),
            ],
            options={
                'db_table': 'clients',
            },
        ),
        migrations.CreateModel(
            name='Onus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=100)),
                ('url_image', models.CharField(max_length=400)),
                ('interfaz_user', models.CharField(max_length=100)),
                ('caja', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apps_utils.cajas')),
                ('estate_onu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_utils.stateonu')),
            ],
            options={
                'db_table': 'onus',
            },
        ),
    ]
