# Generated by Django 5.1.3 on 2024-11-15 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apps_tecnic', '0001_initial'),
        ('apps_utils', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.JSONField()),
                ('direction', models.CharField(max_length=100)),
                ('date_activity', models.CharField(max_length=20)),
                ('prioridad', models.CharField(max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_utils.clients')),
                ('state_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_tecnic.statesaverias')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'activities',
            },
        ),
    ]
