# Generated by Django 5.1.3 on 2024-11-15 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apps_utils', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatesAverias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=100)),
                ('detail', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'states_averias',
            },
        ),
        migrations.CreateModel(
            name='Averias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.JSONField(default=dict)),
                ('date_reporte', models.CharField(max_length=20)),
                ('prioridad', models.CharField(max_length=20)),
                ('date_resolution', models.CharField(max_length=20)),
                ('comentario', models.CharField(max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_utils.clients')),
                ('encargado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('state_averia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_tecnic.statesaverias')),
            ],
        ),
    ]
